langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3-max-2026-01-23
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3-max-2026-01-23
      log-requests: true
      log-responses: true



logging:
  level:
    dev.langchain4j: DEBUG

spring:
  data:
    redis:
      port: 13854
      host: redis-13854.c294.ap-northeast-1-2.ec2.cloud.redislabs.com
      password: UCB51vDJGhWuhPiiIbsGBurLMiZI5Wuo