langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3-max-2026-01-23
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3-max-2026-01-23
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: text-embedding-v3
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10 #设置一次性最多给向量模型发送的最多数量

  community:
    redis:
      host: 8.222.139.88
      port: 6379



logging:
  level:
    dev.langchain4j: DEBUG

spring:
  data:
    redis:
      host: 8.222.139.88
      port: 6379

#      port: 13854
#      host: redis-13854.c294.ap-northeast-1-2.ec2.cloud.redislabs.com
#      password: UCB51vDJGhWuhPiiIbsGBurLMiZI5Wuo

  datasource:
    url: jdbc:mysql://localhost:3306/volunteer?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true